bank_params:
  count: 10
  # Individual bank configurations - varying sizes and strategies
  individual_banks:
    B00:
      name: "MegaBank"
      strategy: "Maintain"
      size_category: "large"
      equity_start: 50_000_000
      portfolio_balance_start: 500_000_000
      portfolio_rate_start_bps: 480
      image_score: 1.0  # Strong brand
      execution_speed: 1.0  # Slower due to size
      cost_of_funds_bps: 280  # Better funding costs
      operating_cost_per_loan: 800
    B01:
      name: "GrowthBank"
      strategy: "Grow"
      size_category: "medium"
      equity_start: 20_000_000
      portfolio_balance_start: 200_000_000
      portfolio_rate_start_bps: 480
      image_score: 1.0
      execution_speed: 1.0
      cost_of_funds_bps: 280
      operating_cost_per_loan: 800
    B02:
      name: "ChallengerBank"
      strategy: "Grow"
      size_category: "small"
      equity_start: 8_000_000
      portfolio_balance_start: 80_000_000
      portfolio_rate_start_bps: 480
      image_score: 1.0
      execution_speed: 1.0
      cost_of_funds_bps: 280
      operating_cost_per_loan: 800
    B03:
      name: "RegionalBank"
      strategy: "Maintain"
      size_category: "medium"
      equity_start: 15_000_000
      portfolio_balance_start: 150_000_000
      portfolio_rate_start_bps: 480
      image_score: 1.0
      execution_speed: 1.0
      cost_of_funds_bps: 280
      operating_cost_per_loan: 800
    B04:
      name: "FinTech"
      strategy: "Grow"
      size_category: "small"
      equity_start: 5_000_000
      portfolio_balance_start: 50_000_000
      portfolio_rate_start_bps: 480
      image_score: 1.0
      execution_speed: 1.0
      cost_of_funds_bps: 280
      operating_cost_per_loan: 800
    B05:
      name: "EstablishedBank"
      strategy: "Maintain"
      size_category: "large"
      equity_start: 35_000_000
      portfolio_balance_start: 350_000_000
      portfolio_rate_start_bps: 480
      image_score: 1.0
      execution_speed: 1.0
      cost_of_funds_bps: 280
      operating_cost_per_loan: 800
    B06:
      name: "CommunityBank"
      strategy: "Maintain"
      size_category: "small"
      equity_start: 6_000_000
      portfolio_balance_start: 60_000_000
      portfolio_rate_start_bps: 480
      image_score: 1.0
      execution_speed: 1.0
      cost_of_funds_bps: 280
      operating_cost_per_loan: 800
    B07:
      name: "AggressiveGrowth"
      strategy: "Grow"
      size_category: "medium"
      equity_start: 12_000_000
      portfolio_balance_start: 120_000_000
      portfolio_rate_start_bps: 480
      image_score: 1.0
      execution_speed: 1.0
      cost_of_funds_bps: 280
      operating_cost_per_loan: 800
    B08:
      name: "OnlineBank"
      strategy: "Grow"
      size_category: "medium"
      equity_start: 10_000_000
      portfolio_balance_start: 100_000_000
      portfolio_rate_start_bps: 480
      image_score: 1.0
      execution_speed: 1.0
      cost_of_funds_bps: 280
      operating_cost_per_loan: 800
    B09:
      name: "ConservativeBank"
      strategy: "Maintain"
      size_category: "medium"
      equity_start: 18_000_000
      portfolio_balance_start: 180_000_000
      portfolio_rate_start_bps: 480
      image_score: 1.0
      execution_speed: 1.0
      cost_of_funds_bps: 280
      operating_cost_per_loan: 800
  # Default values if not specified per bank
  default_conditions:
    cost_of_funds_bps: 300
    operating_cost_per_loan: 1_000
    equity_start: 10_000_000
    portfolio_balance_start: 100_000_000
    portfolio_rate_start_bps: 500