bank_params:
  count: 10
  # Individual bank configurations - varying sizes and strategies
  individual_banks:
    B00:
      name: "MegaBank"
      strategy: "Maintain"
      size_category: "large"
      equity_start: 50_000_000
      portfolio_balance_start: 500_000_000
      portfolio_rate_start_bps: 480
      image_score: 0.9  # Strong brand
      execution_speed: 0.7  # Slower due to size
      cost_of_funds_bps: 280  # Better funding costs
      operating_cost_per_loan: 800
    B01:
      name: "GrowthBank"
      strategy: "Grow"
      size_category: "medium"
      equity_start: 20_000_000
      portfolio_balance_start: 200_000_000
      portfolio_rate_start_bps: 500
      image_score: 0.6
      execution_speed: 0.8
      cost_of_funds_bps: 300
      operating_cost_per_loan: 1_000
    B02:
      name: "ChallengerBank"
      strategy: "Grow"
      size_category: "small"
      equity_start: 8_000_000
      portfolio_balance_start: 80_000_000
      portfolio_rate_start_bps: 520
      image_score: 0.5
      execution_speed: 0.9  # Fast and nimble
      cost_of_funds_bps: 320  # Higher funding costs
      operating_cost_per_loan: 1_200
    B03:
      name: "RegionalBank"
      strategy: "Maintain"
      size_category: "medium"
      equity_start: 15_000_000
      portfolio_balance_start: 150_000_000
      portfolio_rate_start_bps: 490
      image_score: 0.7
      execution_speed: 0.75
      cost_of_funds_bps: 300
      operating_cost_per_loan: 950
    B04:
      name: "FinTech"
      strategy: "Grow"
      size_category: "small"
      equity_start: 5_000_000
      portfolio_balance_start: 50_000_000
      portfolio_rate_start_bps: 550
      image_score: 0.4
      execution_speed: 0.95  # Very fast
      cost_of_funds_bps: 350  # Highest funding costs
      operating_cost_per_loan: 500  # Low operating costs
    B05:
      name: "EstablishedBank"
      strategy: "Maintain"
      size_category: "large"
      equity_start: 35_000_000
      portfolio_balance_start: 350_000_000
      portfolio_rate_start_bps: 475
      image_score: 0.85
      execution_speed: 0.65
      cost_of_funds_bps: 285
      operating_cost_per_loan: 850
    B06:
      name: "CommunityBank"
      strategy: "Maintain"
      size_category: "small"
      equity_start: 6_000_000
      portfolio_balance_start: 60_000_000
      portfolio_rate_start_bps: 510
      image_score: 0.8  # Strong local reputation
      execution_speed: 0.7
      cost_of_funds_bps: 310
      operating_cost_per_loan: 1_100
    B07:
      name: "AggressiveGrowth"
      strategy: "Grow"
      size_category: "medium"
      equity_start: 12_000_000
      portfolio_balance_start: 120_000_000
      portfolio_rate_start_bps: 520
      image_score: 0.55
      execution_speed: 0.85
      cost_of_funds_bps: 310
      operating_cost_per_loan: 1_050
    B08:
      name: "OnlineBank"
      strategy: "Grow"
      size_category: "medium"
      equity_start: 10_000_000
      portfolio_balance_start: 100_000_000
      portfolio_rate_start_bps: 530
      image_score: 0.45
      execution_speed: 0.92  # Digital efficiency
      cost_of_funds_bps: 330
      operating_cost_per_loan: 600  # Low operating costs
    B09:
      name: "ConservativeBank"
      strategy: "Maintain"
      size_category: "medium"
      equity_start: 18_000_000
      portfolio_balance_start: 180_000_000
      portfolio_rate_start_bps: 485
      image_score: 0.75
      execution_speed: 0.68
      cost_of_funds_bps: 295
      operating_cost_per_loan: 900
  # Default values if not specified per bank
  default_conditions:
    cost_of_funds_bps: 300
    operating_cost_per_loan: 1_000
    equity_start: 10_000_000
    portfolio_balance_start: 100_000_000
    portfolio_rate_start_bps: 500